# Problem 2: Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding 
# the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values 
# do not exceed four million, find the sum of the even-valued terms.
# sum is 4613732

ul = 4000000

i1 = 1
i2 = 2
sum = i2
i = 0
while i <= ul:
	i = i1 + i2
	if i%2 == 0:
		sum += i
	i1 = i2
	i2 = i
	
print sum